import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Divider } from "../SVGcomponents/Divider";
import { IconAdvice } from "../SVGcomponents/IconAdvice";
import { MobileDivider } from "../SVGcomponents/MobileDivider";
import React, { useEffect, useState } from "react";

const URI = "https://api.adviceslip.com/advice";

export default function Home() {

    const [advice, setAdvice] = useState({});
    const getData = async () => {
      const res = await fetch(URI);
      const data = await res.json();
      setAdvice(data);
    };

  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Mentor | Advice generator app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cardContainer}>
          <span className={styles.adviceNumber}> ADVICE {advice.slip ? `#${advice.slip.id}` : "#117"}</span>
          <p
            className={styles.advice}
          >{advice.slip ? `"${advice.slip.advice}"` : `"It is easy to sit up and take notice, what's really difficult is getting up and taking actions"`}</p>
          <Divider className={styles.desktopDivider} />
          <MobileDivider className={styles.mobileDivider} />
        </div>
        <button className={styles.newAdvice} onClick={getData}>
          <IconAdvice />
        </button>
      </main>

      <footer className={styles.footer}>
        <span className={styles.span}>
          Challenge by <a>Frontend Mentor</a>
          {" "}Coded by <a className={styles.a} href="https://twitter.com/_cxalem" target="_blank" rel="noreferrer">Alejandro.</a>
        </span>
      </footer>
    </div>
  );
}
